name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head of the pull request.
          # Only include this option if you are running this workflow on pull requests.
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Installing the pre-requiste
        run: sudo apt-get install python3-setuptools && pip3 install wheel
      - name: Iniatilize the tool
        run: pip3 install gittyleaks
      - name: Perform Scan
        run: python3 -m gittyleaks -repo .
